version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/crates/cli/docker"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
