[package]
name = "bls12381-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
bls12_381 = "0.8.0"
ff = "0.13.0"
rand = "0.8.5"
group = "0.13.0"
